
package gui;

import javax.swing.ImageIcon;

/**
 *
 * @author nicolas
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumno = new javax.swing.JMenu();
        menuFormDeAlumn = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        menuFormDeMateria = new javax.swing.JMenuItem();
        menuAdministracion = new javax.swing.JMenu();
        menuManejDeInsc = new javax.swing.JMenuItem();
        menuManipDeNota = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuAlumnPorMater = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidad ULP");
        setIconImage(new ImageIcon(getClass().getResource("/gui/img/icon-ulp.png")).getImage());
        setPreferredSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.UTILITY);

        desktop.setBackground(new java.awt.Color(74, 112, 122));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/logo-ulp.png"))); // NOI18N

        desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        menuAlumno.setText("Alumno");
        menuAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAlumno.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        menuFormDeAlumn.setText("Formulario de alumno");
        menuFormDeAlumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormDeAlumnActionPerformed(evt);
            }
        });
        menuAlumno.add(menuFormDeAlumn);

        jMenuBar1.add(menuAlumno);

        menuMateria.setText("Materia");
        menuMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuMateria.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        menuFormDeMateria.setText("Formulario de materia");
        menuFormDeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormDeMateriaActionPerformed(evt);
            }
        });
        menuMateria.add(menuFormDeMateria);

        jMenuBar1.add(menuMateria);

        menuAdministracion.setText("Administración");
        menuAdministracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAdministracion.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        menuManejDeInsc.setText("Manejo de inscripciones");
        menuManejDeInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManejDeInscActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuManejDeInsc);

        menuManipDeNota.setText("Manipulación de notas");
        menuManipDeNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManipDeNotaActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuManipDeNota);

        jMenuBar1.add(menuAdministracion);

        menuConsulta.setText("Consultas");
        menuConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConsulta.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        menuAlumnPorMater.setText("Alumnos por materia");
        menuAlumnPorMater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnPorMaterActionPerformed(evt);
            }
        });
        menuConsulta.add(menuAlumnPorMater);

        jMenuBar1.add(menuConsulta);

        menuSalir.setText("Salir");
        menuSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSalir.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFormDeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormDeMateriaActionPerformed
        desktop.removeAll();
        desktop.repaint();
        FormularioDeMateria formdemate = new FormularioDeMateria();
        formdemate.setVisible(true);
        desktop.add(formdemate);
        desktop.add(jLabel1);
    }//GEN-LAST:event_menuFormDeMateriaActionPerformed

    private void menuManejDeInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManejDeInscActionPerformed
        desktop.removeAll();
        desktop.repaint();
        ManejoDeInscripcion manedeinsc = new ManejoDeInscripcion();
        manedeinsc.setVisible(true);
        desktop.add(manedeinsc);
        desktop.add(jLabel1);
    }//GEN-LAST:event_menuManejDeInscActionPerformed

    private void menuFormDeAlumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormDeAlumnActionPerformed
        desktop.removeAll();
        desktop.repaint();
        FormularioDeAlumno formdealum = new FormularioDeAlumno();
        formdealum.setVisible(true);
        desktop.add(formdealum);
        desktop.add(jLabel1);
    }//GEN-LAST:event_menuFormDeAlumnActionPerformed

    private void menuManipDeNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManipDeNotaActionPerformed
        desktop.removeAll();
        desktop.repaint();
        ManipulacionDeNota manidenota = new ManipulacionDeNota();
        manidenota.setVisible(true);
        desktop.add(manidenota);
        desktop.add(jLabel1);
    }//GEN-LAST:event_menuManipDeNotaActionPerformed

    private void menuAlumnPorMaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnPorMaterActionPerformed
        desktop.removeAll();
        desktop.repaint();
        AlumnoPorMateria alumpormate = new AlumnoPorMateria();
        alumpormate.setVisible(true);
        desktop.add(alumpormate);
        desktop.add(jLabel1);
    }//GEN-LAST:event_menuAlumnPorMaterActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSalirMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenuItem menuAlumnPorMater;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuFormDeAlumn;
    private javax.swing.JMenuItem menuFormDeMateria;
    private javax.swing.JMenuItem menuManejDeInsc;
    private javax.swing.JMenuItem menuManipDeNota;
    private javax.swing.JMenu menuMateria;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
